### ISSUE TITLE
A bg was not added in the conf

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/mod-bg-item-reward#4]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Current Behaviour

    ModBGItemReward.AVWinItems
    ModBGItemReward.ABWinItems
    ModBGItemReward.WSGWinItems
    ModBGItemReward.IOCWinItems
    ModBGItemReward.SOTAWinItems
    ModBGItemReward.AVDefeatItems
    ModBGItemReward.ABDefeatItems
    ModBGItemReward.WSGDefeatItems
    ModBGItemReward.IOCDefeatItems
    ModBGItemReward.SOTADefeatItems
    ModBGItemReward.WSGTieItems
       Description: Gives item rewards on battleground victories and defeats.
       Default:     "" - None
        Example      "20558:3" - Warsong Gulch Mark of Honor 3x

ModBGItemReward.AVWinItems = ""
ModBGItemReward.ABWinItems = """
ModBGItemReward.WSGWinItems = ""
ModBGItemReward.IOCWinItems = ""
ModBGItemReward.SOTAWinItems = ""
ModBGItemReward.AVDefeatItems = ""
ModBGItemReward.ABDefeatItems = ""
ModBGItemReward.WSGDefeatItems = ""
ModBGItemReward.IOCDefeatItems = ""
ModBGItemReward.SOTADefeatItems = ""
ModBGItemReward.WSGTieItems = ""

### Expected Blizzlike Behaviour

None

### Steps to reproduce the problem

   ModBGItemReward.EOTSWinItems
    ModBGItemReward.EOTSDefeatItems

ModBGItemReward.EOTSWinItems = ""
ModBGItemReward.EOTSDefeatItems = ""

### Extra Notes

    ModBGItemReward.AVWinItems
    ModBGItemReward.ABWinItems
    ModBGItemReward.EOTSWinItems
    ModBGItemReward.WSGWinItems
    ModBGItemReward.IOCWinItems
    ModBGItemReward.SOTAWinItems
    ModBGItemReward.AVDefeatItems
    ModBGItemReward.ABDefeatItems
    ModBGItemReward.EOTSDefeatItems
    ModBGItemReward.WSGDefeatItems
    ModBGItemReward.IOCDefeatItems
    ModBGItemReward.SOTADefeatItems
    ModBGItemReward.WSGTieItems
       Description: Gives item rewards on battleground victories and defeats.
        Default:     "" - None
        Example      "20558:3" - Warsong Gulch Mark of Honor 3x

ModBGItemReward.AVWinItems = ""
ModBGItemReward.ABWinItems = ""
ModBGItemReward.EOTSWinItems = ""
ModBGItemReward.WSGWinItems = ""
ModBGItemReward.IOCWinItems = ""
ModBGItemReward.SOTAWinItems = ""
ModBGItemReward.AVDefeatItems = ""
ModBGItemReward.ABDefeatItems = ""
ModBGItemReward.EOTSDefeatItems = ""
ModBGItemReward.WSGDefeatItems = ""
ModBGItemReward.IOCDefeatItems = ""
ModBGItemReward.SOTADefeatItems = ""
ModBGItemReward.WSGTieItems = ""
```


### AC rev. hash/commit

AzerothCore rev. c2f6f5b88153

### Operating system

Windows

### Customizations

None

**Comment by WingsOfAltair** [comment]
Dear @poryagholami , This issue was solved in PR #6 and refactored in PR #7 . Please make sure to update to the latest https://github.com/azerothcore/mod-bg-item-reward/tree/master branch to solve the missing implementation of the module.
